name: workflow_pushdocker
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            - name: build image
              run: 
                 
                docker build . -t herreramaxi/spam-modelbuild:latest

            - name: push image to docker hub
              run: |
                docker push herreramaxi/spam-modelbuild:latest

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: ${{ secrets.GCP_PROJECT }}
                service_account_key: ${{ secrets.GCP_CREDENTIALS }}
                export_default_credentials: true

            - name: Get GKE credentials
              run: |
                gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
                  --region ${{ secrets.GKE_REGION }} \
                  --project ${{ secrets.GCP_PROJECT }}

            - name: Deploy to GKE
              run: |
                kubectl apply -f kubernetes/
                kubectl rollout status deployment/spam-app