name: workflow_pushdocker
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            #Comment temporarly
            # - name: build image
            #   run: 
                 
            #     docker build . -t herreramaxi/spam-modelbuild:latest

            # - name: push image to docker hub
            #   run: |
            #     docker push herreramaxi/spam-modelbuild:latest

            # 1. Authenticate using a service account key
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

            # 2. Set up the gcloud CLI
            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: ${{ secrets.GCP_PROJECT }}

            # 3. Get credentials for your GKE cluster
            - name: Get GKE credentials
              run: |
                gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
                  --region ${{ secrets.GKE_REGION }} \
                  --project ${{ secrets.GCP_PROJECT }}

            - name: Deploy to GKE
              env:
                USE_GKE_GCLOUD_AUTH_PLUGIN: "False"
              run: |
                kubectl apply -f kubernetes/
                kubectl rollout status deployment/spam-app