name: workflow_pushdocker
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            - name: build image
              run: 
                 
                docker build . -t herreramaxi/spam-modelbuild:latest

            - name: push image to docker hub
              run: |
                docker push herreramaxi/spam-modelbuild:latest
           
            - name: Authenticate to Google Cloud
              uses: "google-github-actions/auth@v2"
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

            - uses: "google-github-actions/setup-gcloud@v2"
              with:
                install_components: "gke-gcloud-auth-plugin"

            - name: Authenticate to GKE cluster
              uses: google-github-actions/get-gke-credentials@v2
              with:
                cluster_name: hello-cluster
                location: europe-west4

            - name: Deploy to GKE
              # env:
              #   USE_GKE_GCLOUD_AUTH_PLUGIN: "False"
              run: |
                kubectl apply -f kubernetes/
                kubectl rollout status deployment/spam-app